// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhrpevdffmuezoveovmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ocnBldmRmZm11ZXpvdmVvdm1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNjg0NjQsImV4cCI6MjA2MDk0NDQ2NH0.lrJv4yteRP5EIt-7YMt350kDL-HcTLkvepYef4vtv6w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);